version: 2

sources:
  - name: jaffle_shop
    database: raw  # Tell dbt to look for the source in the "raw" database
    
    tables:
      - name: orders

        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

        loaded_at_field: _ETL_LOADED_AT

      - name: customers
    
  - name: stripe
    database: raw  # Tell dbt to look for the source in the "raw" database
    tables:
      - name: payment